### ISSUE TITLE
Unable to run Cloning_with_GC_constant_sh_vXII_60.slim

### ISSUE THREAD

**Issue by logankblair** [dominik-kopcak/SelfClonGC#1]
Hello,

Great paper, and I am really interested in how you implemented mitotic gene conversion in SLiM. However, I haven't been able to get Cloning_with_GC_constant_sh_vXII_60.slim to run successfully. 

I have tried copying the script into SLiMgui (v4.3) and adding some dummy values for GC_rate, lambda, the selection coefficient, etc. However, the simulation is always crashing on the third tick.

Would you mind including the command line arguments in the readme?

**Comment by dominik-kopcak** [comment]
Hi,

Thank you for your interest. Upon rising the issue, I added a simplified bash script by which I run the simulation, and a file with parameters used. I hope this will allow you to run it successfully, but please let me know if not.

**Comment by logankblair** [comment]
Thank you, it works with the parameters in the .txt file.
